package com.alexander.springboot.insumotronics.enums;

public enum ProductCategory {
    GENERAL,
    RESISTENCIAS,
    CAPACITORES,
    INDUCTORES,
    DIODOS,
    TRANSISTORES,
    CIRCUITOS_INTEGRADOS,
    MICROCONTROLADORES,
    SENSORES,
    LEDS_Y_DISPLAYS,
    CONECTORES_Y_CABLES,
    FUENTES_DE_ALIMENTACION,
    PROTOBOARD_Y_HERRAMIENTAS,
    BATERIAS_Y_CARGADORES,
    RELEVADORES_Y_ACTUADORES
}
